### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by omershlo**

### CODE REVIEW

**Comment by oleiba** [comment]
A few words about specific motivation?
any impact of upgraded dependencies?

**Comment by omershlo** [comment]
following multi party ecdsa audit. 
My tests passed, but double check

**Comment by oleiba** [comment]
I am getting this:
```
error[E0635]: unknown feature `cfg_doctest`
  --> /Users/odedleiba/.cargo/registry/src/github.com-1ecc6299db9ec823/memoffset-0.5.2/src/lib.rs:60:40
   |
60 | #![cfg_attr(memoffset_nightly, feature(cfg_doctest))]
   |                                        ^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by oleiba** [comment]
The latest comment was solved after I upgraded to latest using rustup.

Now I have 2 issues:
1. Schnorr test fails, not consistently:
```
---- test::tests::test_schnorr stdout ----
(req schnorr/keygen/first, took: PT0.006323757S)
(req schnorr/keygen/6be12709-d406-4914-860b-b6476e6c25de/second, took: PT0.005862634S)
(req schnorr/keygen/6be12709-d406-4914-860b-b6476e6c25de/third, took: PT0.004524078S)
(req schnorr/keygen/first, took: PT0.003543560S)
(req schnorr/keygen/5fb972f2-ad29-4d27-9f3a-20068518198e/second, took: PT0.003857609S)
(req schnorr/keygen/5fb972f2-ad29-4d27-9f3a-20068518198e/third, took: PT0.022913922S)
thread 'test::tests::test_schnorr' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:378:21
```

1. I get lots of warnings I don't currently get on master:
```
warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:187:18
    |
187 | ) -> Result<Json<(party_one::PDLFirstMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses
    |
    = note: `#[warn(unused_parens)]` on by default

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:226:18
    |
226 | ) -> Result<Json<(party_one::PDLSecondMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:260:18
    |
260 | ) -> Result<Json<(Party1FirstMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:299:18
    |
299 | ) -> Result<Json<(Party1SecondMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:380:18
    |
380 | ) -> Result<Json<(party_one::EphKeyGenFirstMsg)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:416:18
    |
416 | ) -> Result<Json<(party_one::SignatureRecid)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:457:18
    |
457 | ) -> Result<Json<(coin_flip_optimal_rounds::Party1FirstMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:539:18
    |
539 | ) -> Result<Json<(party_one::PDLFirstMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:587:18
    |
587 | ) -> Result<Json<(party_one::PDLSecondMessage)>> {
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove these parentheses

warning: unnecessary parentheses around type
   --> /Users/odedleiba/MyWorkspace/gotham-city/gotham-server/src/routes/ecdsa.rs:640:80
    |
640 | pub fn recover(state: State<Config>, claim: Claims, id: String) -> Result<Json<(u32)>> {
    |                                                                                ^^^^^ help: remove these parentheses

    Finished test [unoptimized + debuginfo] target(s) in 0.48s
     Running target/debug/deps/tests-f6cc1c42a7d3de0b
```

**Comment by omershlo** [comment]
Thanks,
1) Schnorr: I can't reproduce your failure. How many times did you run it? I did however needed to change the port from 8000 to 8001 in ALL three integration tests to make them run. Is it possible you forgot to change the port in schnorr integration test?

2) This is the same warning many times. It was introduced in the new version of Rust. I cleaned it from some repos and I guess we can completely clean it next time we commit. I find that the parentheses are helpful some times, If you insist I will clear it..

**Comment by oleiba** [comment]
1. Actually I got it on the first try. Next few times it passed.
   It's not related to the port because it also passes...
2. I suggest either removing the parentheses or removing the rule of warning about them...
    Having so many warnings for the project is annoying and distracts more meaningful warnings...

**Comment by omershlo** [comment]
@oleiba any luck reproducing the error ?

**Comment by oleiba** [comment]
No. Approving.

**Pull request closed without merging**
